modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "create_so"
version = "${version}"
displayName = "Create: Sandpaper Overhaul"
authors = "Ghasto69"
description = '''
Create: Sandpaper Overhaul is an addon to the Create Mod that adds more uses and variation to sandpaper!
'''
logoFile = "icon.png"

[[dependencies.create_so]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_so]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"